### ISSUE TITLE
Cannot add ledger named "rdfs/void"

### ISSUE THREAD

**Issue by alan-deronyan** [fluree/server#37]
I can't add a ledger named "rdfs/void"!! 

Client (swagger / postman) consistently hangs on my request, and the server throws some exceptions (attached below). 

I also tried a bunch of variations of this path which all succeed (see my screenshot of the docker volume contents), so this specific path is perhaps reserved (it's the [VOID](https://www.w3.org/TR/void/) dataset vocabulary) for internal use!?!?

Request Body:
```
{
    "ledger": "rdfs/void"
}
```

curl:
```
curl --location 'http://localhost:58090/fluree/create' \
--header 'Content-Type: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "ledger": "rdfs/void"
}'
```

Server Logs:
```
17:08:47.938 [async-dispatch-6] WARN  f.s.consensus.handlers.create-ledger - "Ledger id is already pending creation: rdfs/void"
17:08:47.939 [async-dispatch-6] INFO  fluree.server.handlers.create - Ledger created: nil
17:08:47.939 [clojure-agent-send-off-pool-10] INFO  fluree.db.json-ld.api - Creating ledger nil
Exception in thread "async-dispatch-6" java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "x" is null
        at clojure.lang.Numbers.ops(Numbers.java:1095)
        at clojure.lang.Numbers.minus(Numbers.java:131)
        at fluree.server.handlers.create$create_ledger$fn__69651$state_machine__14611__auto____69670$fn__69672.invoke(create.clj:63)
        at fluree.server.handlers.create$create_ledger$fn__69651$state_machine__14611__auto____69670.invoke(create.clj:41)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:971)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:976)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:974)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__14629.invoke(ioc_macros.clj:985)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__9672$fn__9673.invoke(channels.clj:100)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__9575$fn__9576.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "async-dispatch-7" java.lang.NullPointerException: Cannot invoke "Object.toString()" because "s" is null
        at clojure.string$starts_with_QMARK_.invokeStatic(string.clj:365)
        at clojure.string$starts_with_QMARK_.invoke(string.clj:361)
        at fluree.db.json_ld.api$address_QMARK_.invokeStatic(api.cljc:104)
        at fluree.db.json_ld.api$address_QMARK_.invoke(api.cljc:100)
        at fluree.db.json_ld.api$exists_QMARK_$fn__61975$state_machine__14611__auto____61980$fn__61982.invoke(api.cljc:152)
        at fluree.db.json_ld.api$exists_QMARK_$fn__61975$state_machine__14611__auto____61980.invoke(api.cljc:151)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:971)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:976)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:974)
        at fluree.db.json_ld.api$exists_QMARK_$fn__61975.invoke(api.cljc:151)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__9575$fn__9576.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Unknown Source)
17:08:47.940 [async-dispatch-5] ERROR fluree.db.json-ld.api - #error {
 :cause "Cannot invoke \"Object.toString()\" because \"s\" is null"
 :via
 [{:type java.lang.NullPointerException
   :message "Cannot invoke \"Object.toString()\" because \"s\" is null"
   :at [clojure.string$starts_with_QMARK_ invokeStatic "string.clj" 365]}]
 :trace
 [[clojure.string$starts_with_QMARK_ invokeStatic "string.clj" 365]
  [clojure.string$starts_with_QMARK_ invoke "string.clj" 361]
  [fluree.db.ledger.json_ld$normalize_alias invokeStatic "json_ld.cljc" 191]
  [fluree.db.ledger.json_ld$normalize_alias invoke "json_ld.cljc" 188]
  [fluree.db.ledger.json_ld$create_STAR_$fn__58612$state_machine__14611__auto____58619$fn__58622 invoke "json_ld.cljc" 239]
  [fluree.db.ledger.json_ld$create_STAR_$fn__58612$state_machine__14611__auto____58619 invoke "json_ld.cljc" 214]
  [clojure.core.async.impl.ioc_macros$run_state_machine invokeStatic "ioc_macros.clj" 972]
  [clojure.core.async.impl.ioc_macros$run_state_machine invoke "ioc_macros.clj" 971]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invokeStatic "ioc_macros.clj" 976]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invoke "ioc_macros.clj" 974]
  [fluree.db.ledger.json_ld$create_STAR_$fn__58612 invoke "json_ld.cljc" 214]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__9575$fn__9576 invoke "concurrent.clj" 29]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run nil -1]]}
17:08:47.940 [clojure-agent-send-off-pool-10] ERROR f.s.components.consensus-handler - "Unexpected error in processor function for event :ledger-create with message: Cannot invoke \"Object.toString()\" because \"s\" is null"
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "s" is null
        at clojure.string$starts_with_QMARK_.invokeStatic(string.clj:365)
        at clojure.string$starts_with_QMARK_.invoke(string.clj:361)
        at fluree.db.ledger.json_ld$normalize_alias.invokeStatic(json_ld.cljc:191)
        at fluree.db.ledger.json_ld$normalize_alias.invoke(json_ld.cljc:188)
        at fluree.db.ledger.json_ld$create_STAR_$fn__58612$state_machine__14611__auto____58619$fn__58622.invoke(json_ld.cljc:239)
        at fluree.db.ledger.json_ld$create_STAR_$fn__58612$state_machine__14611__auto____58619.invoke(json_ld.cljc:214)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:971)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:976)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:974)
        at fluree.db.ledger.json_ld$create_STAR_$fn__58612.invoke(json_ld.cljc:214)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__9575$fn__9576.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Attached screen grab of docker volume hierarchy:
![Screenshot 2024-02-09 at 12 05 01 PM](https://github.com/fluree/server/assets/127438337/714fe6b0-c433-4798-b16d-3d766996fbd0)

**Comment by alan-deronyan** [comment]
Additional note - restarting the server doesn't help. Only wiping the data volume fixes it.

**Comment by alan-deronyan** [comment]
One additional note - a simple insert with just an "@id" value also causes the hang. e.g....

```{"ledger": "foo/bar","insert": [{ "@id": "foo" }]}``

is invalid.
